// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// Firebase is not currently used in this project.
// This file is kept as a placeholder for future Firebase integration.

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Placeholder [FirebaseOptions] class for future Firebase integration.
class FirebaseOptions {
  final String apiKey;
  final String appId;
  final String messagingSenderId;
  final String projectId;
  final String? authDomain;
  final String? storageBucket;
  final String? measurementId;
  final String? iosBundleId;

  const FirebaseOptions({
    required this.apiKey,
    required this.appId,
    required this.messagingSenderId,
    required this.projectId,
    this.authDomain,
    this.storageBucket,
    this.measurementId,
    this.iosBundleId,
  });
}

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTWpm9Gbrt81iKRbReCcx-aEP2m41ukFk',
    appId: '1:926300397430:web:510191006e9e06fb956457',
    messagingSenderId: '926300397430',
    projectId: 'habitforge-9869a',
    authDomain: 'habitforge-9869a.firebaseapp.com',
    storageBucket: 'habitforge-9869a.firebasestorage.app',
    measurementId: 'G-RCPEHCC9BH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc5fs4awbqG-0QjpKXuEu3sXmkcf6qg74',
    appId: '1:926300397430:android:a1d534cae584559b956457',
    messagingSenderId: '926300397430',
    projectId: 'habitforge-9869a',
    storageBucket: 'habitforge-9869a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeSMAYgqvNjDYV3KXcA8i7Vz0avHdOz84',
    appId: '1:926300397430:ios:bde3cc3f3d77784a956457',
    messagingSenderId: '926300397430',
    projectId: 'habitforge-9869a',
    storageBucket: 'habitforge-9869a.firebasestorage.app',
    iosBundleId: 'com.example.HabitForge.habitforge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeSMAYgqvNjDYV3KXcA8i7Vz0avHdOz84',
    appId: '1:926300397430:ios:bde3cc3f3d77784a956457',
    messagingSenderId: '926300397430',
    projectId: 'habitforge-9869a',
    storageBucket: 'habitforge-9869a.firebasestorage.app',
    iosBundleId: 'com.example.HabitForge.habitforge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTWpm9Gbrt81iKRbReCcx-aEP2m41ukFk',
    appId: '1:926300397430:web:553fd6698bcf18d0956457',
    messagingSenderId: '926300397430',
    projectId: 'habitforge-9869a',
    authDomain: 'habitforge-9869a.firebaseapp.com',
    storageBucket: 'habitforge-9869a.firebasestorage.app',
    measurementId: 'G-1NJCD6LD1X',
  );
}
