import 'package:flutter/material.dart';
import '../models/habit_model.dart';

class AppConstants {
  static const String appName = 'HabitForge';
  static const String version = '1.0.0';

  static const List<Color> accentColors = [
    Color(0xFF4CAF50),
    Color(0xFF2196F3),
    Color(0xFFE91E63),
    Color(0xFFFF9800),
    Color(0xFF9C27B0),
    Color(0xFF00BCD4),
    Color(0xFFFF5722),
    Color(0xFF607D8B),
    Color(0xFF795548),
    Color(0xFF3F51B5),
  ];

  static const List<int> habitColors = [
    0xFF4CAF50,
    0xFF2196F3,
    0xFFE91E63,
    0xFFFF9800,
    0xFF9C27B0,
    0xFF00BCD4,
    0xFFFF5722,
    0xFF607D8B,
    0xFF795548,
    0xFF3F51B5,
    0xFF009688,
    0xFFCDDC39,
    0xFFFFC107,
    0xFF673AB7,
    0xFF03A9F4,
    0xFFE040FB,
    0xFF76FF03,
    0xFFFF6E40,
    0xFF448AFF,
    0xFFEEFF41,
  ];

  static const List<String> categories = [
    'Health',
    'Fitness',
    'Mindfulness',
    'Productivity',
    'Learning',
    'Social',
    'Finance',
    'Creativity',
    'General',
  ];

  static const Map<String, String> categoryEmojis = {
    'Health': '❤️',
    'Fitness': '💪',
    'Mindfulness': '🧘',
    'Productivity': '⚡',
    'Learning': '📚',
    'Social': '👥',
    'Finance': '💰',
    'Creativity': '🎨',
    'General': '✨',
  };

  static const List<String> moodTags = [
    'Energetic',
    'Calm',
    'Stressed',
    'Happy',
    'Anxious',
    'Grateful',
    'Tired',
    'Motivated',
    'Focused',
    'Relaxed',
  ];

  static const List<String> commonEmojis = [
    '💧',
    '🏃',
    '📖',
    '🧘',
    '💪',
    '🥗',
    '😴',
    '✍️',
    '🎯',
    '🧠',
    '🎨',
    '🎵',
    '📝',
    '💻',
    '🌱',
    '🧹',
    '💊',
    '🦷',
    '🚶',
    '🧪',
    '📞',
    '🤝',
    '💰',
    '📊',
    '🎸',
    '📸',
    '🧩',
    '♟️',
    '🎮',
    '🏋️',
    '🚴',
    '🏊',
    '⚽',
    '🎾',
    '🥊',
    '🧗',
    '🏄',
    '🎿',
    '⛷️',
    '🤸',
    '🍎',
    '🥤',
    '☕',
    '🫖',
    '🍳',
    '🥑',
    '🥕',
    '🫁',
    '❤️‍🔥',
    '🔥',
    '⭐',
    '🌟',
    '✨',
    '💎',
    '🏆',
    '🎖️',
    '🥇',
    '🎪',
    '🎭',
    '🎬',
  ];

  static String getQuoteForDay(int dayOfYear) =>
      quotes[dayOfYear % quotes.length];

  static const List<String> quotes = [
    "The secret of getting ahead is getting started. — Mark Twain",
    "It does not matter how slowly you go as long as you do not stop. — Confucius",
    "Success is the sum of small efforts repeated day in and day out. — Robert Collier",
    "We are what we repeatedly do. Excellence is not an act, but a habit. — Aristotle",
    "The only way to do great work is to love what you do. — Steve Jobs",
    "Motivation is what gets you started. Habit is what keeps you going. — Jim Rohn",
    "Small daily improvements over time lead to stunning results. — Robin Sharma",
    "You'll never change your life until you change something you do daily. — John C. Maxwell",
    "The chains of habit are too light to be felt until they are too heavy to be broken. — Warren Buffett",
    "Don't watch the clock; do what it does. Keep going. — Sam Levenson",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "Believe you can and you're halfway there. — Theodore Roosevelt",
    "Your future is created by what you do today, not tomorrow. — Robert Kiyosaki",
    "Success is not final, failure is not fatal: courage to continue counts. — Churchill",
    "What you do every day matters more than what you do once in a while. — Gretchen Rubin",
    "A journey of a thousand miles begins with a single step. — Lao Tzu",
    "Perseverance is not a long race; it is many short races one after the other.",
    "Fall seven times, stand up eight. — Japanese Proverb",
    "The only impossible journey is the one you never begin. — Tony Robbins",
    "Start where you are. Use what you have. Do what you can. — Arthur Ashe",
    "Every moment is a fresh beginning. — T.S. Eliot",
    "Act as if what you do makes a difference. It does. — William James",
    "Discipline is the bridge between goals and accomplishment. — Jim Rohn",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Don't limit your challenges. Challenge your limits.",
    "Push yourself, because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn't just find you. You have to go out and get it.",
    "The key to success is to focus on goals, not obstacles.",
    "Don't stop when you're tired. Stop when you're done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days.",
    "It's going to be hard, but hard does not mean impossible.",
    "Don't wait for opportunity. Create it.",
    "Sometimes later becomes never. Do it now.",
    "The pain you feel today will be the strength you feel tomorrow.",
    "Habits are the compound interest of self-improvement. — James Clear",
    "You do not rise to the level of your goals. You fall to the level of your systems.",
    "Every action you take is a vote for the type of person you wish to become.",
    "Progress, not perfection.",
    "One day or day one. You decide.",
    "Be stronger than your excuses.",
    "It always seems impossible until it's done. — Nelson Mandela",
    "Your only limit is your mind.",
    "Strive for progress, not perfection.",
    "Consistency is what transforms average into excellence.",
    "The way to get started is to quit talking and begin doing. — Walt Disney",
    "If you want something you've never had, do something you've never done.",
    "The future depends on what you do today. — Mahatma Gandhi",
    "Life is 10% what happens to us and 90% how we react to it.",
    "With the new day comes new strength and new thoughts. — Eleanor Roosevelt",
    "It is during our darkest moments that we must focus to see the light.",
    "Setting goals is the first step in turning the invisible into the visible.",
    "Well done is better than well said. — Benjamin Franklin",
    "Quality is not an act, it is a habit. — Aristotle",
    "In the middle of every difficulty lies opportunity. — Albert Einstein",
    "Be the change that you wish to see in the world. — Mahatma Gandhi",
    "If you can dream it, you can do it. — Walt Disney",
    "Life begins at the end of your comfort zone.",
    "What we achieve inwardly will change outer reality. — Plutarch",
    "Happiness is not something ready made. It comes from your own actions.",
    "The mind is everything. What you think you become. — Buddha",
    "Tough times never last but tough people do.",
    "Whether you think you can or you think you can't, you're right. — Henry Ford",
    "I have not failed. I've just found 10,000 ways that won't work. — Edison",
    "Nothing is impossible, the word itself says 'I'm possible'! — Audrey Hepburn",
    "You miss 100% of the shots you don't take. — Wayne Gretzky",
    "Everything you've ever wanted is on the other side of fear.",
    "Build good habits and they will build you.",
    "You are never too old to set another goal or dream a new dream. — C.S. Lewis",
    "Only I can change my life. No one can do it for me. — Carol Burnett",
    "Stay hungry, stay foolish. — Steve Jobs",
    "If opportunity doesn't knock, build a door. — Milton Berle",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "In order to succeed, we must first believe that we can.",
    "Try not to become a person of success, but rather a person of value. — Einstein",
    "Live as if you were to die tomorrow. Learn as if you were to live forever.",
    "The purpose of our lives is to be happy. — Dalai Lama",
    "Love the life you live. Live the life you love. — Bob Marley",
    "Life is really simple, but we insist on making it complicated. — Confucius",
    "Turn your wounds into wisdom. — Oprah Winfrey",
    "Consistency beats intensity.",
    "The difference between ordinary and extraordinary is that little extra.",
    "Don't count the days. Make the days count. — Muhammad Ali",
    "Action is the foundational key to all success. — Pablo Picasso",
    "You don't have to be great to start, but you have to start to be great.",
    "The best revenge is massive success. — Frank Sinatra",
    "If you are not willing to risk the usual, you will have to settle for the ordinary.",
    "I find that the harder I work, the more luck I seem to have. — Thomas Jefferson",
    "Today a reader, tomorrow a leader. — Margaret Fuller",
    "Education is the most powerful weapon which you can use to change the world.",
    "The only person you are destined to become is the person you decide to be.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Keep your face always toward the sunshine and shadows will fall behind you.",
    "May you live all the days of your life. — Jonathan Swift",
    "Not how long, but how well you have lived is the main thing. — Seneca",
    "An unexamined life is not worth living. — Socrates",
    "Life is what happens when you're busy making other plans. — John Lennon",
    "You only live once, but if you do it right, once is enough. — Mae West",
  ];
}

class HabitTemplate {
  final String name;
  final String emoji;
  final String category;
  final HabitType type;
  final int targetCount;
  final double targetValue;
  final String unit;
  final int targetDurationMinutes;
  final String description;

  const HabitTemplate({
    required this.name,
    required this.emoji,
    required this.category,
    this.type = HabitType.boolean,
    this.targetCount = 1,
    this.targetValue = 0,
    this.unit = '',
    this.targetDurationMinutes = 0,
    this.description = '',
  });

  static const List<HabitTemplate> all = [
    HabitTemplate(
      name: 'Drink Water',
      emoji: '💧',
      category: 'Health',
      type: HabitType.count,
      targetCount: 8,
      unit: 'glasses',
    ),
    HabitTemplate(name: 'Take Vitamins', emoji: '💊', category: 'Health'),
    HabitTemplate(
      name: 'Eat Fruits',
      emoji: '🍎',
      category: 'Health',
      type: HabitType.count,
      targetCount: 3,
      unit: 'servings',
    ),
    HabitTemplate(name: 'No Sugar', emoji: '🚫', category: 'Health'),
    HabitTemplate(
      name: 'Sleep 8 Hours',
      emoji: '😴',
      category: 'Health',
      type: HabitType.measurable,
      targetValue: 8,
      unit: 'hours',
    ),
    HabitTemplate(
      name: 'Brush Teeth',
      emoji: '🦷',
      category: 'Health',
      type: HabitType.count,
      targetCount: 2,
      unit: 'times',
    ),
    HabitTemplate(name: 'Skincare', emoji: '🧴', category: 'Health'),
    HabitTemplate(
      name: 'Eat Vegetables',
      emoji: '🥗',
      category: 'Health',
      type: HabitType.count,
      targetCount: 3,
      unit: 'servings',
    ),
    HabitTemplate(
      name: 'Morning Run',
      emoji: '🏃',
      category: 'Fitness',
      type: HabitType.duration,
      targetDurationMinutes: 30,
    ),
    HabitTemplate(
      name: 'Workout',
      emoji: '🏋️',
      category: 'Fitness',
      type: HabitType.duration,
      targetDurationMinutes: 45,
    ),
    HabitTemplate(
      name: 'Walk 10K Steps',
      emoji: '🚶',
      category: 'Fitness',
      type: HabitType.measurable,
      targetValue: 10000,
      unit: 'steps',
    ),
    HabitTemplate(
      name: 'Stretching',
      emoji: '🤸',
      category: 'Fitness',
      type: HabitType.duration,
      targetDurationMinutes: 15,
    ),
    HabitTemplate(
      name: 'Yoga',
      emoji: '🧘',
      category: 'Fitness',
      type: HabitType.duration,
      targetDurationMinutes: 30,
    ),
    HabitTemplate(
      name: 'Push-ups',
      emoji: '💪',
      category: 'Fitness',
      type: HabitType.count,
      targetCount: 50,
      unit: 'reps',
    ),
    HabitTemplate(
      name: 'Meditate',
      emoji: '🧘',
      category: 'Mindfulness',
      type: HabitType.duration,
      targetDurationMinutes: 10,
    ),
    HabitTemplate(
      name: 'Gratitude Journal',
      emoji: '🙏',
      category: 'Mindfulness',
      type: HabitType.count,
      targetCount: 3,
      unit: 'things',
    ),
    HabitTemplate(
      name: 'Deep Breathing',
      emoji: '🌬️',
      category: 'Mindfulness',
      type: HabitType.duration,
      targetDurationMinutes: 5,
    ),
    HabitTemplate(
      name: 'Digital Detox',
      emoji: '📵',
      category: 'Mindfulness',
      type: HabitType.duration,
      targetDurationMinutes: 60,
    ),
    HabitTemplate(name: 'Affirmations', emoji: '✨', category: 'Mindfulness'),
    HabitTemplate(name: 'Plan Tomorrow', emoji: '📝', category: 'Productivity'),
    HabitTemplate(
      name: 'Read',
      emoji: '📖',
      category: 'Productivity',
      type: HabitType.duration,
      targetDurationMinutes: 30,
    ),
    HabitTemplate(
      name: 'No Social Media',
      emoji: '📱',
      category: 'Productivity',
    ),
    HabitTemplate(
      name: 'Deep Work',
      emoji: '🎯',
      category: 'Productivity',
      type: HabitType.duration,
      targetDurationMinutes: 120,
    ),
    HabitTemplate(name: 'Review Goals', emoji: '🏆', category: 'Productivity'),
    HabitTemplate(name: 'Inbox Zero', emoji: '📧', category: 'Productivity'),
    HabitTemplate(
      name: 'Learn Language',
      emoji: '🌍',
      category: 'Learning',
      type: HabitType.duration,
      targetDurationMinutes: 15,
    ),
    HabitTemplate(
      name: 'Online Course',
      emoji: '💻',
      category: 'Learning',
      type: HabitType.duration,
      targetDurationMinutes: 30,
    ),
    HabitTemplate(
      name: 'Practice Coding',
      emoji: '👨‍💻',
      category: 'Learning',
      type: HabitType.duration,
      targetDurationMinutes: 60,
    ),
    HabitTemplate(
      name: 'Read Articles',
      emoji: '📰',
      category: 'Learning',
      type: HabitType.count,
      targetCount: 3,
      unit: 'articles',
    ),
    HabitTemplate(name: 'Teach Someone', emoji: '🎓', category: 'Learning'),
    HabitTemplate(name: 'Call Family', emoji: '📞', category: 'Social'),
    HabitTemplate(name: 'Random Kindness', emoji: '🤝', category: 'Social'),
    HabitTemplate(name: 'Connect with Friend', emoji: '👋', category: 'Social'),
    HabitTemplate(name: 'Track Spending', emoji: '💰', category: 'Finance'),
    HabitTemplate(
      name: 'Save Money',
      emoji: '🏦',
      category: 'Finance',
      type: HabitType.measurable,
      targetValue: 10,
      unit: 'dollars',
    ),
    HabitTemplate(name: 'No Impulse Buying', emoji: '🛑', category: 'Finance'),
    HabitTemplate(
      name: 'Draw/Sketch',
      emoji: '🎨',
      category: 'Creativity',
      type: HabitType.duration,
      targetDurationMinutes: 20,
    ),
    HabitTemplate(
      name: 'Write',
      emoji: '✍️',
      category: 'Creativity',
      type: HabitType.measurable,
      targetValue: 500,
      unit: 'words',
    ),
    HabitTemplate(
      name: 'Play Instrument',
      emoji: '🎸',
      category: 'Creativity',
      type: HabitType.duration,
      targetDurationMinutes: 30,
    ),
  ];
}

class AchievementDefinitions {
  static List<Map<String, dynamic>> get all => [
    {
      'id': 'streak_3',
      'title': 'First Flame',
      'description': '3-day streak',
      'iconEmoji': '🔥',
      'type': 'streak',
      'requiredValue': 3,
      'xpReward': 50,
    },
    {
      'id': 'streak_7',
      'title': 'Week Warrior',
      'description': '7-day streak',
      'iconEmoji': '⚔️',
      'type': 'streak',
      'requiredValue': 7,
      'xpReward': 100,
    },
    {
      'id': 'streak_14',
      'title': 'Fortnight Fighter',
      'description': '14-day streak',
      'iconEmoji': '🛡️',
      'type': 'streak',
      'requiredValue': 14,
      'xpReward': 150,
    },
    {
      'id': 'streak_30',
      'title': 'Monthly Master',
      'description': '30-day streak',
      'iconEmoji': '👑',
      'type': 'streak',
      'requiredValue': 30,
      'xpReward': 250,
    },
    {
      'id': 'streak_60',
      'title': 'Double Down',
      'description': '60-day streak',
      'iconEmoji': '💎',
      'type': 'streak',
      'requiredValue': 60,
      'xpReward': 350,
    },
    {
      'id': 'streak_100',
      'title': 'Century Club',
      'description': '100-day streak',
      'iconEmoji': '💯',
      'type': 'streak',
      'requiredValue': 100,
      'xpReward': 500,
    },
    {
      'id': 'streak_365',
      'title': 'Year Champion',
      'description': '365-day streak',
      'iconEmoji': '🏆',
      'type': 'streak',
      'requiredValue': 365,
      'xpReward': 1000,
    },
    {
      'id': 'comp_1',
      'title': 'First Step',
      'description': 'Complete 1 habit',
      'iconEmoji': '👣',
      'type': 'completion',
      'requiredValue': 1,
      'xpReward': 10,
    },
    {
      'id': 'comp_10',
      'title': 'Getting Started',
      'description': 'Complete 10 habits',
      'iconEmoji': '🌱',
      'type': 'completion',
      'requiredValue': 10,
      'xpReward': 50,
    },
    {
      'id': 'comp_50',
      'title': 'Habit Maker',
      'description': 'Complete 50 habits',
      'iconEmoji': '🌿',
      'type': 'completion',
      'requiredValue': 50,
      'xpReward': 100,
    },
    {
      'id': 'comp_100',
      'title': 'Centurion',
      'description': 'Complete 100 habits',
      'iconEmoji': '🌳',
      'type': 'completion',
      'requiredValue': 100,
      'xpReward': 200,
    },
    {
      'id': 'comp_500',
      'title': 'Habit Machine',
      'description': 'Complete 500 habits',
      'iconEmoji': '⚙️',
      'type': 'completion',
      'requiredValue': 500,
      'xpReward': 350,
    },
    {
      'id': 'comp_1000',
      'title': 'Unstoppable',
      'description': 'Complete 1000 habits',
      'iconEmoji': '🚀',
      'type': 'completion',
      'requiredValue': 1000,
      'xpReward': 500,
    },
    {
      'id': 'create_1',
      'title': 'The Beginning',
      'description': 'Create first habit',
      'iconEmoji': '🎯',
      'type': 'creation',
      'requiredValue': 1,
      'xpReward': 25,
    },
    {
      'id': 'create_5',
      'title': 'Planner',
      'description': 'Create 5 habits',
      'iconEmoji': '📋',
      'type': 'creation',
      'requiredValue': 5,
      'xpReward': 75,
    },
    {
      'id': 'create_10',
      'title': 'Ambitious',
      'description': 'Create 10 habits',
      'iconEmoji': '🌟',
      'type': 'creation',
      'requiredValue': 10,
      'xpReward': 150,
    },
    {
      'id': 'perfect_day',
      'title': 'Perfect Day',
      'description': 'Complete all habits in a day',
      'iconEmoji': '⭐',
      'type': 'perfect_day',
      'requiredValue': 1,
      'xpReward': 50,
    },
    {
      'id': 'perfect_week',
      'title': 'Perfect Week',
      'description': '7 perfect days in a row',
      'iconEmoji': '🌈',
      'type': 'perfect_week',
      'requiredValue': 7,
      'xpReward': 200,
    },
    {
      'id': 'level_5',
      'title': 'Rising Star',
      'description': 'Reach level 5',
      'iconEmoji': '⭐',
      'type': 'level',
      'requiredValue': 5,
      'xpReward': 100,
    },
    {
      'id': 'level_10',
      'title': 'Veteran',
      'description': 'Reach level 10',
      'iconEmoji': '🎖️',
      'type': 'level',
      'requiredValue': 10,
      'xpReward': 200,
    },
    {
      'id': 'level_20',
      'title': 'Elite',
      'description': 'Reach level 20',
      'iconEmoji': '👑',
      'type': 'level',
      'requiredValue': 20,
      'xpReward': 400,
    },
    {
      'id': 'level_30',
      'title': 'Legend',
      'description': 'Reach max level',
      'iconEmoji': '🏆',
      'type': 'level',
      'requiredValue': 30,
      'xpReward': 1000,
    },
    {
      'id': 'mood_7',
      'title': 'Self Aware',
      'description': 'Log mood 7 days',
      'iconEmoji': '🪞',
      'type': 'mood',
      'requiredValue': 7,
      'xpReward': 50,
    },
    {
      'id': 'mood_30',
      'title': 'Emotionally Intelligent',
      'description': 'Log mood 30 days',
      'iconEmoji': '💭',
      'type': 'mood',
      'requiredValue': 30,
      'xpReward': 150,
    },
  ];
}
