import 'package:flutter/material.dart';

class AppConstants {
  static const List<Color> accentColors = [
    Color(0xFF6750A4),
    Color(0xFF2196F3),
    Color(0xFF4CAF50),
    Color(0xFFFF9800),
    Color(0xFFE91E63),
    Color(0xFF9C27B0),
    Color(0xFF00BCD4),
    Color(0xFFFF5722),
    Color(0xFF607D8B),
    Color(0xFF795548),
  ];

  static const List<Color> habitColors = [
    Color(0xFFEF5350),
    Color(0xFFEC407A),
    Color(0xFFAB47BC),
    Color(0xFF7E57C2),
    Color(0xFF5C6BC0),
    Color(0xFF42A5F5),
    Color(0xFF29B6F6),
    Color(0xFF26C6DA),
    Color(0xFF26A69A),
    Color(0xFF66BB6A),
    Color(0xFF9CCC65),
    Color(0xFFD4E157),
    Color(0xFFFFEE58),
    Color(0xFFFFCA28),
    Color(0xFFFFA726),
    Color(0xFFFF7043),
    Color(0xFF8D6E63),
    Color(0xFFBDBDBD),
    Color(0xFF78909C),
    Color(0xFF546E7A),
  ];

  static const List<String> categories = [
    'Health',
    'Fitness',
    'Mindfulness',
    'Productivity',
    'Learning',
    'Social',
    'Finance',
    'Creativity',
    'Custom',
  ];

  static const List<String> categoryEmojis = [
    '❤️',
    '💪',
    '🧘',
    '⚡',
    '📚',
    '👥',
    '💰',
    '🎨',
    '⭐',
  ];

  static const List<String> moodTags = [
    'Energetic',
    'Calm',
    'Stressed',
    'Happy',
    'Anxious',
    'Grateful',
    'Tired',
    'Motivated',
  ];

  static const List<String> emojis = [
    '💧',
    '🏃',
    '📖',
    '🧘',
    '💪',
    '🥗',
    '😴',
    '📝',
    '🎯',
    '⏰',
    '🌅',
    '🌙',
    '☕',
    '🍎',
    '🥤',
    '🚶',
    '🧠',
    '💊',
    '🦷',
    '🧼',
    '🛏️',
    '📱',
    '💻',
    '🎵',
    '🎨',
    '📸',
    '✍️',
    '🗣️',
    '👨‍👩‍👧',
    '🐕',
    '🌱',
    '♻️',
    '💰',
    '📊',
    '🏠',
    '🧹',
    '👔',
    '🎓',
    '🏋️',
    '🚴',
    '🏊',
    '⚽',
    '🎾',
    '🧗',
    '🥊',
    '🧘‍♂️',
    '🤸',
    '💃',
    '🎮',
    '📺',
    '🎪',
    '🎭',
    '🎲',
    '🧩',
    '♟️',
    '🎻',
    '🎸',
    '🥁',
    '🎤',
    '🎬',
    '📰',
    '✈️',
    '🚗',
    '🚲',
    '🛒',
    '🍳',
    '🥘',
    '🍕',
    '🥙',
    '🍲',
    '🥑',
    '🥦',
    '🍌',
    '🍇',
    '🍊',
    '🍓',
    '🫐',
    '🥛',
    '🍵',
    '🧃',
    '💤',
    '🧴',
    '💅',
    '🪥',
    '🧊',
    '🔥',
    '⭐',
    '🌟',
    '💎',
    '🏆',
    '🎖️',
    '🥇',
    '🌈',
    '☀️',
    '🌊',
    '🍀',
    '🦋',
    '🌸',
    '🌺',
    '🌻',
    '🌾',
    '🍂',
    '❄️',
    '⛄',
    '🎁',
    '🎉',
    '🎊',
    '💝',
    '💌',
    '🕊️',
    '🦅',
    '🐱',
    '🐶',
    '🐠',
    '🦜',
    '🐢',
    '🦊',
    '🐼',
    '🦁',
    '🐨',
    '🧸',
    '🎒',
    '👟',
    '🧢',
    '👓',
    '⌚',
    '📿',
    '🗝️',
    '🔔',
    '📌',
    '✅',
    '❌',
    '❓',
    '💡',
    '🔋',
    '🧲',
    '🔬',
    '🔭',
    '⚗️',
    '🧪',
    '💉',
    '🩺',
    '🩹',
    '🧬',
    '📅',
    '📆',
    '🗓️',
    '📇',
    '📋',
    '📁',
    '📂',
    '🗂️',
    '📐',
    '📏',
    '✂️',
    '🖊️',
    '🖋️',
    '✒️',
    '📎',
    '🔗',
    '🧮',
    '📣',
    '📢',
    '🔊',
    '🔉',
    '🔈',
    '🔇',
    '🎙️',
    '📻',
    '🎚️',
    '🎛️',
    '⏱️',
    '⏲️',
    '⏰',
    '🕰️',
    '⌛',
    '⏳',
    '🗺️',
    '🧭',
    '🏔️',
    '⛰️',
    '🏖️',
    '🏝️',
    '🏜️',
    '🌋',
    '🗻',
    '🏕️',
    '🏗️',
    '🏢',
    '🏠',
    '🏡',
    '🏘️',
    '⛪',
    '🕌',
    '🛕',
    '⛩️',
    '🏯',
    '🏰',
  ];

  static const List<String> quotes = [
    "We are what we repeatedly do. Excellence is not an act, but a habit.",
    "The secret of getting ahead is getting started.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Small daily improvements over time lead to stunning results.",
    "Success is the sum of small efforts repeated day in and day out.",
    "Motivation is what gets you started. Habit is what keeps you going.",
    "The only way to do great work is to love what you do.",
    "Don't watch the clock; do what it does. Keep going.",
    "Believe you can and you're halfway there.",
    "You don't have to be great to start, but you have to start to be great.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "Your habits shape your identity, and your identity shapes your habits.",
    "Every action you take is a vote for the type of person you wish to become.",
    "Habits are the compound interest of self-improvement.",
    "The difference between who you are and who you want to be is what you do.",
    "A journey of a thousand miles begins with a single step.",
    "It's not about perfect. It's about effort.",
    "Push yourself because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn't just find you. You have to go out and get it.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don't stop when you're tired. Stop when you're done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days.",
    "It's going to be hard, but hard does not mean impossible.",
    "Don't wait for opportunity. Create it.",
    "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream it. Believe it. Build it.",
    "Stay positive. Work hard. Make it happen.",
    "Your limitation—it's only your imagination.",
    "Sometimes later becomes never. Do it now.",
    "Discipline is choosing between what you want now and what you want most.",
    "You are never too old to set another goal or to dream a new dream.",
    "Consistency is what transforms average into excellence.",
    "Make each day your masterpiece.",
    "The pain you feel today will be the strength you feel tomorrow.",
    "Don't decrease the goal. Increase the effort.",
    "Results happen over time, not overnight.",
    "Work while they sleep. Learn while they party. Save while they spend.",
    "The only person you should try to be better than is who you were yesterday.",
    "Don't count the days. Make the days count.",
    "Strive for progress, not perfection.",
    "Fall seven times, stand up eight.",
    "What you do every day matters more than what you do once in a while.",
    "If you want something you've never had, you must do something you've never done.",
    "Tough times don't last. Tough people do.",
    "Act as if what you do makes a difference. It does.",
    "With the new day comes new strength and new thoughts.",
    "It always seems impossible until it's done.",
    "Quality is not an act, it is a habit.",
    "Start where you are. Use what you have. Do what you can.",
    "The future depends on what you do today.",
    "Knowing is not enough; we must apply. Willing is not enough; we must do.",
    "Well done is better than well said.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Setting goals is the first step in turning the invisible into the visible.",
    "All progress takes place outside the comfort zone.",
    "A year from now you may wish you had started today.",
    "Champions keep playing until they get it right.",
    "I find that the harder I work, the more luck I seem to have.",
    "If you are not willing to risk the usual, you will have to settle for the ordinary.",
    "The way to get started is to quit talking and begin doing.",
    "In the middle of every difficulty lies opportunity.",
    "Don't be afraid to give up the good to go for the great.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Creativity is intelligence having fun.",
    "Opportunities don't happen. You create them.",
    "If you can dream it, you can do it.",
    "There are no shortcuts to any place worth going.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "The mind is everything. What you think you become.",
    "An investment in knowledge pays the best interest.",
    "Change your thoughts and you change your world.",
    "You miss 100% of the shots you don't take.",
    "Everything you've ever wanted is on the other side of fear.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "Two roads diverged in a wood, and I took the one less traveled by.",
    "The best revenge is massive success.",
    "I attribute my success to this: I never gave or took any excuse.",
    "If you look at what you have in life, you'll always have more.",
    "Very little is needed to make a happy life; it is all within yourself.",
    "Go confidently in the direction of your dreams.",
    "When I let go of what I am, I become what I might be.",
    "Life shrinks or expands in proportion to one's courage.",
    "What we achieve inwardly will change outer reality.",
    "Life is either a daring adventure or nothing at all.",
    "To handle yourself, use your head; to handle others, use your heart.",
    "Too many of us are not living our dreams because we are living our fears.",
    "If you want to lift yourself up, lift up someone else.",
    "I have learned over the years that when one's mind is made up, this diminishes fear.",
    "I alone cannot change the world, but I can cast a stone across the water to create many ripples.",
    "Nothing is impossible, the word itself says I'm possible.",
    "One person can make a difference, and everyone should try.",
    "Happiness is not something ready made. It comes from your own actions.",
    "The purpose of our lives is to be happy.",
    "Life is what happens when you're busy making other plans.",
    "Get busy living or get busy dying.",
    "You only live once, but if you do it right, once is enough.",
  ];

  static String getQuoteForToday() {
    final dayOfYear =
        DateTime.now().difference(DateTime(DateTime.now().year, 1, 1)).inDays;
    return quotes[dayOfYear % quotes.length];
  }

  static const Map<int, String> levelNames = {
    1: 'Beginner',
    2: 'Novice',
    3: 'Apprentice',
    4: 'Student',
    5: 'Learner',
    6: 'Practitioner',
    7: 'Skilled',
    8: 'Competent',
    9: 'Proficient',
    10: 'Adept',
    11: 'Advanced',
    12: 'Expert',
    13: 'Specialist',
    14: 'Veteran',
    15: 'Master',
    16: 'Grand Master',
    17: 'Elite',
    18: 'Champion',
    19: 'Hero',
    20: 'Titan',
    21: 'Mythic',
    22: 'Immortal',
    23: 'Divine',
    24: 'Celestial',
    25: 'Cosmic',
    26: 'Transcendent',
    27: 'Ethereal',
    28: 'Supreme',
    29: 'Ultimate',
    30: 'Legend',
  };

  static const Map<int, int> levelXPThresholds = {
    1: 0,
    2: 100,
    3: 250,
    4: 500,
    5: 800,
    6: 1200,
    7: 1700,
    8: 2300,
    9: 3000,
    10: 3800,
    11: 4700,
    12: 5700,
    13: 6800,
    14: 8000,
    15: 9500,
    16: 11000,
    17: 13000,
    18: 15000,
    19: 17500,
    20: 20000,
    21: 23000,
    22: 26500,
    23: 30000,
    24: 34000,
    25: 38500,
    26: 43000,
    27: 47000,
    28: 50000,
    29: 53000,
    30: 50000,
  };

  static int getLevelForXP(int xp) {
    int level = 1;
    for (final entry in levelXPThresholds.entries) {
      if (xp >= entry.value) level = entry.key;
    }
    return level;
  }
}
